
const USER_TYPE = {
  USER: 'USER'
};

const STATUS = {
  ACTIVE  : 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED : 'DELETED',
};

const CHAT_MESSAGE_STATUS = {
  SEEN     : 'SEEN',
  NOT_SEEN : 'NOT_SEEN',
  DELETED  : 'DELETED',
}

const NOTIFICATION_TYPE = {
  PUSH: 'PUSH',
  NORMAL: 'NORMAL'
}

const DEFAULT_PAGE_NUMBER = 1;
const DEFAULT_PAGE_SIZE   = 10;

const VOTE_TYPE = {
  UPVOTE  : 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
}

const VOTE_FOR = {
  POST   : 'POST',
  COMMENT: 'COMMENT',
}

export default {
  VOTE_FOR,
  VOTE_TYPE,
  USER_TYPE,
  CHAT_MESSAGE_STATUS,
  NOTIFICATION_TYPE,
  DEFAULT_PAGE_NUMBER,
  DEFAULT_PAGE_SIZE,
  STATUS,
}