
const EVENTS = {
  ROOM_JOINED: 'ROOM_JOINED',
  MESSAGE: 'MESSAGE',
  POST_ADDED: 'POST_ADDED',
  POST_LIKED: 'POST_LIKED',
  POST_UNLIKED: 'POST_UNLIKED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  FRIEND_ADDED: 'FRIEND_ADDED',
  FRIEND_REQUESTED: 'FRIEND_REQUESTED',
  NOTIFICATION: 'NOTIFICATION'
};

export default {
  EVENTS,
}